"""add movie owner

Revision ID: 502b06e5acf4
Revises: 8e68d10db151
Create Date: 2026-09-28 17:25:05.874002

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '502b06e5acf4'
down_revision: Union[str, Sequence[str], None] = '8e68d10db151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dim_movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by_user_id', sa.String(length=36), nullable=True))
        batch_op.create_index(batch_op.f('ix_dim_movies_created_by_user_id'), ['created_by_user_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_dim_movies_created_by_user_id_users'), 'users', ['created_by_user_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('movie_watches', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_movie_watch_user_movie'), type_='unique')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_watches', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_movie_watch_user_movie'), ['user_id', 'sk_movie_id'])

    with op.batch_alter_table('dim_movies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_dim_movies_created_by_user_id_users'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_dim_movies_created_by_user_id'))
        batch_op.drop_column('created_by_user_id')

    # ### end Alembic commands ###
