"""add movie watches

Revision ID: 8e68d10db151
Revises: 0a2af3f52f63
Create Date: 2026-09-28 10:33:29.370481

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '8e68d10db151'
down_revision: Union[str, Sequence[str], None] = '0a2af3f52f63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie_watches',
    sa.Column('sk_movie_watch_id', sa.String(length=64), nullable=False),
    sa.Column('sk_movie_id', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('watched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['sk_movie_id'], ['dim_movies.sk_movie_id'], name=op.f('fk_movie_watches_sk_movie_id_dim_movies'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_movie_watches_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sk_movie_watch_id', name=op.f('pk_movie_watches')),
    sa.UniqueConstraint(
    "user_id",
    "sk_movie_id",
    name="uq_movie_watch_user_movie",
),
    )
    with op.batch_alter_table('movie_watches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movie_watches_sk_movie_id'), ['sk_movie_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movie_watches_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movie_watches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movie_watches_user_id'))
        batch_op.drop_index(batch_op.f('ix_movie_watches_sk_movie_id'))

    op.drop_table('movie_watches')
    # ### end Alembic commands ###
